events {}

http {
  upstream backend {
    server server1:7777;
    server server2:7777;
    server server3:7777;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend/;
    }
  }
}