services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: spa-frontend
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
