services:
  static:
    build:
      context: ./static
      dockerfile: Dockerfile
    container_name: nginx-static
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    networks:
      - nginx-net
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nginx-server
    ports:
      - "7777:7777"
    networks:
      - nginx-net

networks:
  nginx-net: